

all : simple complex lultra

simple : simple.c ser.c ser.h 
	gcc simple.c ser.c -o simple


complex : complex.c ser.c ser.h 
	gcc complex.c ser.c -o complex


lultra : lultra.c ser.c ser.h 
	gcc lultra.c ser.c -o lultra


clean :
	rm -f simple
	rm -f complex
	rm -f lultra


